
[[dependencies]]
  branch = "master"
  name = "github.com/anacrolix/torrent"

[[dependencies]]
  name = "github.com/elazarl/go-bindata-assetfs"
  revision = "9a6736ed45b44bf3835afeebb3034b57ed329f3e"

[[dependencies]]
  name = "github.com/jpillora/backoff"
  revision = "a6f64285fd4072883335339357436b78d62c96a4"

[[dependencies]]
  name = "github.com/jpillora/go-realtime"
  revision = "c8b52e99fa07b59183859c03304ea01f04e4921f"

[[dependencies]]
  name = "github.com/jpillora/opts"
  revision = "3f7962811f238e35bdbd9a74cbfcd45b209dd298"

[[dependencies]]
  name = "github.com/jpillora/requestlog"
  revision = "86703d0d0f95a393137e71e94606c2a8c04e8c4f"

[[dependencies]]
  name = "github.com/jpillora/scraper"
  revision = "e773d84ba120c0de5dcbdb7ba07eb6c7ce4d3425"

[[dependencies]]
  name = "github.com/skratchdot/open-golang"
  revision = "75fb7ed4208cf72d323d7d02fd1a5964a7a9073c"
